# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='name',
            field=models.CharField(default='test', max_length=254),
            preserve_default=False,
        ),
    ]
