# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0003_auto_20160921_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaming',
            old_name='date',
            new_name='init_date',
        ),
        migrations.RenameField(
            model_name='streaming',
            old_name='time',
            new_name='init_time',
        ),
        migrations.RenameField(
            model_name='streaming',
            old_name='user_email',
            new_name='user',
        ),
    ]
