# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0005_auto_20160922_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='duration',
            field=models.CharField(choices=[(b'1', b'1 Hora'), (b'30', b'30 Minutos'), (b'15', b'15 Minutos')], default=b'30', max_length=2),
        ),
    ]
