# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0006_streaming_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
