# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0010_auto_20160925_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='init_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 27, 19, 42, 44, 304256, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
