# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0011_streaming_init_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaming',
            name='init_date',
        ),
        migrations.RemoveField(
            model_name='streaming',
            name='init_time',
        ),
    ]
