# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0012_auto_20160927_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 27, 22, 24, 44, 984052, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
