# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0013_streaming_init_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='init_date',
            field=models.DateField(),
        ),
    ]
