# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-29 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamingapp', '0014_auto_20160927_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='droplet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
